version: "3"
services:
  backend:
    build: ./backend-fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./backend-fastapi/.env
    restart: always

  frontend:
    build: ./frontend-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always

